version: 1
script:
  - mkdir build
  - cd build
  - cmake ../source_code
  - make


  - make install DESTDIR=../AppDir
AppDir:
  path: ./AppDir
  app_info:
    id: com.filecxx.FileCentipede
    name: FileCentipede
    icon: filecentipede
    version: 1.0.0
    exec: usr/bin/filecentipede
  files:
    exclude:
      - usr/share/man
      - usr/share/doc
      - usr/share/info
  runtime:
    env:
      LD_LIBRARY_PATH: ${APPDIR}/usr/lib:${APPDIR}/usr/lib/x86_64-linux-gnu