name: Build and Release AppImage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Qt6
        run: |
          sudo apt update
          sudo apt install -y qt6-base-dev qt6-tools-dev-tools qt6-qmake

      - name: Install dependencies
        run: |
          sudo apt install -y cmake build-essential

      - name: Build FileCentipede
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target install DESTDIR=AppDir

      - name: Prepare AppImage
        run: |
          wget https://github.com/AppImageCrafters/build-appimage/releases/download/v1.0.0/appimage-builder-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage
          ./appimage-builder-x86_64.AppImage --recipe AppImageBuilder.yml

      - name: Upload AppImage as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FileCentipede-AppImage
          path: AppDir/*.AppImage

      - name: Create GitHub Release and Upload AppImage
        uses: ghcr.io/softprops/action-gh-release@v1
        with:
          files: AppDir/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
