name: Build FileCentipede AppImage (Linux x86_64, Qt6)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential cmake libssl-dev \
            qt6-base-dev qt6-tools-dev qt6-tools-dev-tools \
            qt6-l10n-tools qt6-base-dev-tools \
            linuxdeploy wget patchelf fuse libfuse2

      - name: Set environment for Qt6
        run: |
          echo "QT_SELECT=qt6" >> $GITHUB_ENV
          echo "/usr/lib/qt6/bin" >> $GITHUB_PATH

      - name: Create build directory
        run: mkdir build

      - name: Configure with CMake (Qt6)
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/qt6

      - name: Build the project
        run: |
          cd build
          make -j$(nproc)

      - name: Download linuxdeploy and plugins
        run: |
          mkdir -p appimage-tools
          cd appimage-tools
          wget -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage
          wget -c https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy-plugin-qt-x86_64.AppImage

      - name: Build AppImage
        run: |
          cd build
          mkdir -p AppDir/usr/bin
          cp FileCentipede AppDir/usr/bin/

          cd ..
          ./appimage-tools/linuxdeploy-x86_64.AppImage --appdir build/AppDir \
            -d FileCentipede.desktop \
            -i resources/logo.png \
            --plugin qt \
            --output appimage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: FileCentipede-x86_64.AppImage
          path: ./*.AppImage
